### ISSUE TITLE
Enhancing Sentry Reports: Displaying Language, Modules, and Extra Data

### ISSUE THREAD

**Issue by butschster** [buggregator/frontend#103]
First of all, we can identify the language used in a report by looking at the payload.platform and linking it with `payload.contexts.runtime`. 

**Here's an example:**

```json
"payload": {
    ...
    "platform": "php",
    "contexts": {
      "runtime": {
        "name": "php",
        "version": "8.2.5"
      }
    },
    ...
}
```

Sentry also provides a list of PHP modules under `payload.modules`. 

**For instance:**

```json
"payload": {
    ...
    "modules": {
      "asm89/stack-cors": "v2.1.1",
      "brick/math": "0.11.0",
      "clue/stream-filter": "v1.6.0",
      "dflydev/dot-access-data": "v3.0.2",
      "doctrine/inflector": "2.0.6",
      "doctrine/instantiator": "2.0.0",
      "doctrine/lexer": "3.0.0",
       ...
    },
}
```

Additionally, Sentry provides `extra` data in a flexible format:

```json
"payload": {
    ...
    "extra": {
     "environment": {
        "SHELL": "/bin/bash",
        "WSL2_GUI_APPS_ENABLED": "1",
        "WSL_DISTRO_NAME": "Ubuntu-22.04",
        "NODE_OPTIONS": "--openssl-legacy-provider",
        "NAME": "ButschsterLpp",
        ...
      },
      ...
    },
}
```

It would be beneficial if we could display all these details on a Sentry page.

1. **Language/Runtime Version**: This could be displayed within the "Tags" section or as a separate block adjacent to it, clearly labeled with the language and version number for quick identification.
    
2. **Modules**: A new expandable section titled "Modules" could be added below the "Tags" section. It should list the modules in a scrollable format with the ability to expand/collapse for detailed viewing.
    
3. **Extra Data**: This could be shown at the bottom or as a sidebar panel that can be toggled on and off. It should be in a free-form text area or a table that allows for easy scanning of the various environmental variables and settings.

---

And funny picture from DALL-E with suggestion on how to display this data

![image](https://github.com/buggregator/frontend/assets/773481/32908381-a2ef-405f-be59-dccef30b5766)

**Comment by Kreezag** [comment]
added in #197
