### ISSUE TITLE
VarDump - Please encose string dumps with double quotes

### ISSUE THREAD

**Issue by FluffyDiscord** [buggregator/frontend#12]
Sometimes, I happen to dump empty strings, for example `  ` (three standard spaces), but the buggregator does not show that there are only spaces in the VarDump. It should behave like console dump does, eg. show double quotes around the string value. The right way would be to use VarDump in buggregator too, render the sent dump and send the whole HTML to the browser.

**Comment by Kreezag** [comment]
Fixed in [662b7a0](https://github.com/buggregator/frontend/commit/662b7a0df566726856cb3bece3c98eb93136b4c4)

Will be available in next release.
