### ISSUE TITLE
Feature: open event in another tab

### ISSUE THREAD

**Issue by roxblnfk** [buggregator/frontend#131]
Add the ability to open an event in another tab (window).
It should be any event (dump, email, sentry...)

**Comment by Kreezag** [comment]
@roxblnfk thanks for your request.
You may open event in the new tab by click on middle button of mouse to open link in new tab. It works for all events that has own pages. 
The ability to open in new page shor events (var damper or monolog) we need to complete issue #142

**Comment by roxblnfk** [comment]
Looks solved
