### ISSUE TITLE
Bug: can''t unpause on main tab

### ISSUE THREAD

**Issue by roxblnfk** [buggregator/frontend#157]
![image](https://github.com/buggregator/frontend/assets/4152481/7e2b6591-71f4-4864-8d8b-dc55a92df300)

Flow:
1. Receive a few `var-dump` events
2. Pause  on the main tab
3. Go to the `var-dumps` tab
4. Click `Clear events`
5. Go to the main tab

**Comment by Kreezag** [comment]
Thanks @roxblnfk for finding this bug!

**Comment by roxblnfk** [comment]
Fixed with #159
