### ISSUE TITLE
Add ability to disable menu items

### ISSUE THREAD

**Issue by farti22** [buggregator/frontend#175]
**What do I want to see?**
In the settings, you can select the menu items that will be displayed in the left sidebar

**What for?**
There are more menu items and they are a little overloaded, with the condition that most likely not all the features of the buggregator are used by a certain service

It's a small thing, but it would be nice

**Comment by Kreezag** [comment]
It looks like a duplicate with #74 
We just working on the feature and done the first step. 
For now it is possible to build own buggregator docker file with selected events on the FE part.
Second step will be moving this settings from env variables to back-end api

**Comment by Kreezag** [comment]
Duplicated issue #74
