### ISSUE TITLE
Display buggregator version in interface

### ISSUE THREAD

**Issue by antonkomarev** [buggregator/frontend#19]
It will be helpful to see what buggregator version is working right now somewhere in the UI.

Related:
- buggregator/server#6

**Comment by butschster** [comment]
@Kreezag you can find information about API method and response for mock here https://github.com/buggregator/server/pull/65

I've prepared a simple example where a version should be displayed.

![Version](https://github.com/buggregator/frontend/assets/773481/d86736ab-7708-4851-97b5-51f1e142bfb1)

**Comment by Kreezag** [comment]
Fixed and added to the release [v0.2.0](https://github.com/buggregator/frontend/releases/tag/0.2.0)
