### ISSUE TITLE
Incorrect `calls` measure format

### ISSUE THREAD

**Issue by gam6itko** [buggregator/frontend#2]
I guess `calls` must be of `int` type.
![image](https://github.com/buggregator/spiral-app/assets/3841197/7d17d70d-8819-4e8b-92d8-942e923d5163)

**Comment by Kreezag** [comment]
Fixed in [c864f72](https://github.com/buggregator/frontend/commit/c864f728e1418a78bfe9432df7e2671900ebff1a)

Will be available in next release.
