### ISSUE TITLE
Display profile information on hover 

### ISSUE THREAD

**Issue by butschster** [buggregator/frontend#20]
When I hover on any call graph node 

![image](https://github.com/buggregator/frontend/assets/773481/253e6fc2-b681-4c89-8ec4-4da5901e3464)

I should see a popup with information about it

![image](https://github.com/buggregator/frontend/assets/773481/c3650cbd-ffc3-42ab-b823-2d9ae2e25e7a)

**Comment by Kreezag** [comment]
Fixed and added to the release [v0.1.2](https://github.com/buggregator/frontend/releases/tag/v0.1.2)
