### ISSUE TITLE
Sentry SVG not centered in Safari

### ISSUE THREAD

**Issue by maantje** [buggregator/frontend#219]
Hey,

When using Safari the Sentry logo is not centered. Removing `preserveAspectRatio="xMinYMin meet"` from `src/shared/ui/icon-svg/icon-svg-originals/sentry.svg` resolves the issue.

Safari:

With `preserveAspectRatio="xMinYMin meet"            |  Without `preserveAspectRatio="xMinYMin meet"
:-------------------------:|:-------------------------:
![](https://github.com/user-attachments/assets/a5fbb8ea-b914-4d88-bb44-330ee199798f)  |  ![](https://github.com/user-attachments/assets/246bd129-1ac1-44cc-89e0-b78bbf9b29fa)

Chrome:

With `preserveAspectRatio="xMinYMin meet"            |  Without `preserveAspectRatio="xMinYMin meet"
:-------------------------:|:-------------------------:
![image](https://github.com/user-attachments/assets/f0ad727d-ded8-4039-a46e-6c6b41aba8fe)  |  ![image](https://github.com/user-attachments/assets/059f4a1b-0a22-4d51-aca2-aa9c65e75475)

Firefox:

With `preserveAspectRatio="xMinYMin meet"            |  Without `preserveAspectRatio="xMinYMin meet"
:-------------------------:|:-------------------------:
![image](https://github.com/user-attachments/assets/3917196a-1436-4d4c-9b2d-e73b97ec0b0e)  |  ![image](https://github.com/user-attachments/assets/5586e678-2dfc-439a-9277-d27748fd9288)

**Comment by Kreezag** [comment]
@maantje thank you for this issue. I'm going to do improve it this week.
