### ISSUE TITLE
Monolog messages shows incorrectly formatted JSON

### ISSUE THREAD

**Issue by nsrosenqvist** [buggregator/frontend#222]
*I'm not entirely sure this is the correct component to file this report against, please let me know if the issue should in fact be reported against another repository*

When I log a message with an "extra" property in the payload, Buggregator shows the related JSON incorrectly. Each property under *extra* gets presented as its own object, creating a lot of noise in the Monolog view. Here is what it looks like for me (with sensitive data redacted:

<img width="793" alt="342325021-cb062965-72af-4a73-a8ca-60bbc42694c7" src="https://github.com/user-attachments/assets/baf00fde-b76f-401e-a35a-35036c34e0d6">

**Actual payload:**
```json
{
    "uuid": "019059fe-9284-71fe-9e47-a392664a8c87",
    "project": null,
    "type": "monolog",
    "payload": {
        "channel": "application",
        "context": {
            "cool": "heck yeah",
            "here": "where?"
        },
        "datetime": "2024-06-27T15:59:34.201624+02:00",
        "extra": {
            "callType": null,
            "class": null,
            "file": "[REDACTED]",
            "function": "[REDACTED]",
            "http_method": "GET",
            "instance": "[REDACTED]",
            "ip": "[REDACTED]",
            "line": 514,
            "referrer": null,
            "server": "[REDACTED]",
            "url": "[REDACTED]"
        },
        "level": 200,
        "level_name": "INFO",
        "message": "Hello world"
    },
    "timestamp": 1719496774.2804
}
```

**Comment by Kreezag** [comment]
HI @nsrosenqvist 
Thanks for the request!

**Comment by nsrosenqvist** [comment]
@Kreezag Thanks for the quick resolution to the issue!
