### ISSUE TITLE
Extra signs after coma

### ISSUE THREAD

**Issue by butschster** [buggregator/frontend#23]
![image](https://github.com/buggregator/frontend/assets/773481/5284510a-6044-4f3c-a6aa-cbaab7c371e8)

**Comment by gam6itko** [comment]
should be like `1m 29s 75ms`

**Comment by Kreezag** [comment]
Fixed in PR
Format will be changed to requested format.

Example:
<img width="418" alt="Components : StatBoard - Large Peaks ⋅ Storybook 2023-08-22 11-26-45" src="https://github.com/buggregator/frontend/assets/13301570/4e241536-a07a-427c-babf-7a99f92914f5">
