### ISSUE TITLE
Improve XHProf tool 

### ISSUE THREAD

**Issue by butschster** [buggregator/frontend#28]
- [x] Improve information in tree
- [x] Threshold settings in tree
- [x] Add sorting on left sidebar by memory, CPU
- [x] Add hover on tree node
- [x] Check if path with bottleneck is highlighted
- [x] Improve d3 tree rerender performance

**Comment by Kreezag** [comment]
Fixed and added to the release [v0.1.2](https://github.com/buggregator/frontend/releases/tag/0.1.2)
