### ISSUE TITLE
Ray database queries show up as empty strings

### ISSUE THREAD

**Issue by Semdevmaster** [buggregator/frontend#42]
Ray database queries show up as empty strings but when clicking the json button in the log line in json I can see the expected query
![image](https://github.com/buggregator/server/assets/2706508/7e734d08-8118-4178-9564-0f6778edb088)
![image](https://github.com/buggregator/server/assets/2706508/651813d8-3cd8-4997-8180-e2f0d1215d7f)

**Comment by butschster** [comment]
There were a component in old version, probably https://github.com/buggregator/laravel-app/blob/master/resources/js/Components/Ray/Payloads/Query.vue and we need to implement it here

**Comment by butschster** [comment]
Hi, @Semdevmaster 
Thanks for the bug report!

**Comment by butschster** [comment]
Hi, @Semdevmaster 
Could you try the latest version? 
I've just checked it
![image](https://github.com/buggregator/frontend/assets/773481/e7587861-5f76-4ef8-8a11-b6b3dc51b102)

**Comment by Semdevmaster** [comment]
Unfortunately the problem remains, I'm using pgsql, maybe this is the problem?
Sql formatting errors are visible in the browser console
Docker image - ghcr.io/buggregator/server:1.0-rc11

![image](https://github.com/buggregator/frontend/assets/2706508/aed09991-09bf-435f-b841-388613558c80)
