### ISSUE TITLE
Empty strings by exceptions in ray module

### ISSUE THREAD

**Issue by Semdevmaster** [buggregator/frontend#44]
Empty strings by exceptions in ray module
In ui empty stings

![image](https://github.com/buggregator/frontend/assets/2706508/6994af0b-3594-4371-ab01-69fdee7e0867)

In browser console full exception content

![image](https://github.com/buggregator/frontend/assets/2706508/9bf0b30f-4241-4522-b75c-24a0f871a2c4)

**Comment by Kreezag** [comment]
@butschster Could you take a look into data? As I see the `projectId` prop is `incompatable` with our types. FE part waited for `project_id` instead of `projectId`
