### ISSUE TITLE
FK. Third tab "Table"

### ISSUE THREAD

**Issue by gam6itko** [buggregator/frontend#59]
It's will be very useful to make similar table like in https://hub.docker.com/r/tuimedia/xhprof-docker

![image](https://github.com/buggregator/frontend/assets/3841197/acc10be1-fe8b-4f28-9ad1-7a164645527b)

with right section
![image](https://github.com/buggregator/frontend/assets/3841197/58955b00-1460-4978-a174-6d0eb78f71d7)

**Comment by Kreezag** [comment]
Thank you for your request.
We will implement this feature to our feature list of new version!
Now we have big rework of the code in progress, and we will take this feature after finishing.
