### ISSUE TITLE
FR: Ability to pause profiles autorefresh.

### ISSUE THREAD

**Issue by gam6itko** [buggregator/frontend#6]
It's hard to find a specific profile when the profiles page in autorefreshing mode. It is necessary to add the ability to pause the loading of a new profiles. For example, you can pause it when the scroll down and trigger it back when it scrolls back on top.

**Comment by Kreezag** [comment]
Available in the release [0.1.0](https://github.com/buggregator/frontend/releases/tag/0.1.0)
