### ISSUE TITLE
Broken mobile and desktop email preview height

### ISSUE THREAD

**Issue by FluffyDiscord** [buggregator/frontend#66]
![image](https://github.com/buggregator/frontend/assets/10332247/c58546e3-c20e-4991-bbcb-78c29a9278f6)

The mobile preview sometimes works, and sometimes doesn't.

**Comment by butschster** [comment]
You mean window height?

**Comment by FluffyDiscord** [comment]
Yes

**Comment by binaryfire** [comment]
I'm getting the same problem. The issue is with the window height on the desktop preview (the third icon)

**Comment by butschster** [comment]
Hello @binaryfire @FluffyDiscord! I released a new version. Could you check?

**Comment by binaryfire** [comment]
@butschster Yep, all good now. Thanks!
