### ISSUE TITLE
Ray `showQueries` info not displaying on frontend

### ISSUE THREAD

**Issue by binaryfire** [buggregator/frontend#71]
Hi guys

It seems like Ray's `showQueries` method isn't displaying any info on the frontend. We should be able to see the list of queries, execution time etc. Instead, this is what I see in Buggregator:

<img width="872" alt="image" src="https://github.com/buggregator/frontend/assets/5361908/e6b4b943-dd37-4092-9585-dd77f4d6d00e">

But when I visit the JSON link the data is all there. So I think it's a frontend issue.

**Comment by butschster** [comment]
Hi! Could you provide Buggregator's version?

**Comment by binaryfire** [comment]
Hi @butschster. It's v0.2.0 (shown in the bottom left corner of the UI)

**Comment by binaryfire** [comment]
@butschster Oops, I just realised I've been pulling `ghcr.io/buggregator/server:dev` instead of `ghcr.io/buggregator/server:latest`. Changed to `latest` and it's working. Sorry :)

Closing
