### ISSUE TITLE
Feature request: flags to hide unused features

### ISSUE THREAD

**Issue by binaryfire** [buggregator/frontend#74]
It'd be great to have ENV flags to disable unused features (hide them from the dashboard).

For example we're using Mailpit for local email, Laravel Telescope for logging and we're not using XHProf. We've added Buggregator to our Docker local dev environment and we'd like to hide these tabs in the UI. It will reduce clutter and help prevent junior developers from getting confused.

**Comment by Kreezag** [comment]
Thanks for your request. It is really great idea!

**Comment by Kreezag** [comment]
@butschster Do we have a plan to implement feature filter on the server side?
