### ISSUE TITLE
Feature request: Add PWA functionality 

### ISSUE THREAD

**Issue by iftaras** [buggregator/frontend#77]
It would be super useful if the frontend had PWA (Progressive Web App) functionality so we could "install" it on our machines and use it independently from the browser.

**Comment by butschster** [comment]
Sound good!

**Comment by Kreezag** [comment]
Yes, we can do it.  It is not difficult but I'm not sure how it will connect with our existing code,

**Comment by Kreezag** [comment]
completed in #221
