### ISSUE TITLE
Display proper Framework

### ISSUE THREAD

**Issue by gander** [buggregator/frontend#85]
When not using laravel - don't show `Laravel Version`
When using Symfony - show `Symfony Version`
When other framework - don't show anything

![obraz](https://github.com/buggregator/server/assets/421597/3b9ff3f4-9150-42ad-9e7b-b3e83b865923)

**Comment by butschster** [comment]
Based on information from spatie repositories we need to rework approach with handling meta information.

1. For Ray symfony package we need to use `payload.meta.symfony_version` - https://github.com/spatie/ray-bundle/blob/master/src/Ray.php#L115
2. For Ray laravel package we need to use `payload.meta.laravel_version` - https://github.com/spatie/laravel-ray/blob/main/src/Ray.php#L504
3. For Ray yii version use `payload.meta.yii_version` - https://github.com/spatie/yii-ray/blob/master/src/Ray.php#L104

Probably we just need to display all information from meta, or have some filter for keys
