### ISSUE TITLE
[Feature Request] Copy image to clipboard

### ISSUE THREAD

**Issue by roxblnfk** [buggregator/frontend#95]
Rework the **save image as file** button to:
- 1 click - copy to clipboard
- double-click - save as file

Why? In most cases we don't need to save a dump image as a file - we use clipboard to paste the image in a telegram message or forum page or issue tracker.

The options also may be placed in a dropdown with text. It might be more clear

**Comment by Kreezag** [comment]
Updated in version 1.12.0
