### ISSUE TITLE
Improve Span Context Display in Inspector Report

### ISSUE THREAD

**Issue by butschster** [buggregator/frontend#96]
The current display of the Inspector Report in Buggregator presents each span with associated context, such as SQL queries and their duration, directly next to the span. This can lead to a cluttered interface and make it difficult for users to quickly scan and understand the report.

**Proposed Solution:**
Rework the display of context information for each span to enhance clarity. The context should not be displayed inline with the span but should instead be available as a tooltip that appears when a user hovers over or clicks on the span block. This change aims to make the interface cleaner and the data more digestible at a glance.

Attached is a screenshot from the current Inspector Report interface, illustrating the issue with inline context display.
![image](https://github.com/buggregator/frontend/assets/773481/63816f43-992a-46d3-a892-6c9932407c8c)

---

And funny picture from DALL-E with suggestion on how to display this data

![image](https://github.com/buggregator/frontend/assets/773481/a0f83166-4f8c-4b65-b91f-93ad88fbe217)

**Comment by Kreezag** [comment]
@butschster Could you please add description ?

**Comment by butschster** [comment]
> @butschster Could you please add description ?

Done

**Comment by Kreezag** [comment]
This request is relevant only for inspector page.

**Comment by Kreezag** [comment]
fixed in #215
