### ISSUE TITLE
[FEATURE] Open link in IDE

### ISSUE THREAD

**Issue by gander** [buggregator/frontend#98]
Provide support to allow opening file location like in [Symfony Profiler](https://symfony.com/doc/current/reference/configuration/framework.html#ide) for:

+ `phpstorm`
+ `sublime`
+ `textmate`
+ `macvim`
+ `emacs`
+ `atom`
+ `vscode`

**Comment by butschster** [comment]
Hi @Kreezag 
I've added a new option to set the API endpoint. Here's what the updated Settings API response looks like:

```json
{
    "auth": {
      "enabled": false,
      "login_url": "/login"
    },
    "ide": {
      "url_template": "phpstorm://open?url=file://${file}&line=${line}"
    },
    "version":"'0.0.0"
}
```

The `ide.url_template` contains a template where you need to replace `${file}` with the actual file path and `${line}` with the line number.

It would be great to create a component for such cases, where users can click on a file path and it will open in the IDE as specified. This could streamline development workflows significantly.

Here is an example what can be replaced
![image](https://github.com/buggregator/frontend/assets/773481/fd65a3fd-899b-4ffb-aafc-bba7c07f4101)

**Comment by Kreezag** [comment]
Feature was added in https://github.com/buggregator/frontend/pull/186 and released in https://github.com/buggregator/frontend/releases/tag/1.21.1
